FROM python:3.9
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY *.py /app
EXPOSE 9001
CMD ["uvicorn", "exam:app", "--host", "0.0.0.0", "--port", "9001"]
